"""renames departments

Revision ID: 758aa43ac2bf
Revises: 9a68b5ffd634
Create Date: 2024-03-13 17:49:36.191580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758aa43ac2bf'
down_revision = '9a68b5ffd634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", "departments")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departments", "department")
